version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: appointments_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appointments
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appointments_api
    restart: unless-stopped
    env_file:
      - .env         
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  db_data:
