name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    # сервисный контейнер Postgres
    services:
      db:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: appointments
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4          # клонирует ваш репозиторий
      - uses: actions/setup-python@v5      # ставит Python 3.12
        with:
          python-version: "3.12"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Lint
        run: make lint

      - name: Tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/appointments
        run: make test

      - name: Build & push Docker image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
